# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 886)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 221))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 61, 24))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lineEdit_latitude = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_latitude.setGeometry(QtCore.QRect(100, 30, 161, 24))
        self.lineEdit_latitude.setObjectName("lineEdit_latitude")
        self.lineEdit_longitude = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_longitude.setGeometry(QtCore.QRect(100, 60, 161, 24))
        self.lineEdit_longitude.setObjectName("lineEdit_longitude")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 81, 24))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_speed = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_speed.setGeometry(QtCore.QRect(100, 90, 81, 24))
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 81, 24))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 81, 24))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_gps_status = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_gps_status.setGeometry(QtCore.QRect(100, 120, 161, 24))
        self.lineEdit_gps_status.setObjectName("lineEdit_gps_status")
        self.lineEdit_gps_mode = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_gps_mode.setGeometry(QtCore.QRect(100, 150, 161, 24))
        self.lineEdit_gps_mode.setObjectName("lineEdit_gps_mode")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 81, 24))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 81, 24))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_gps_time = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_gps_time.setGeometry(QtCore.QRect(100, 180, 181, 24))
        self.lineEdit_gps_time.setText("")
        self.lineEdit_gps_time.setObjectName("lineEdit_gps_time")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(830, 850, 111, 24))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 10, 621, 461))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(40, 370, 91, 41))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_altitude = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_altitude.setGeometry(QtCore.QRect(40, 420, 91, 24))
        self.lineEdit_altitude.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_altitude.setObjectName("lineEdit_altitude")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(200, 370, 91, 41))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.lineEdit_pressure = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pressure.setGeometry(QtCore.QRect(200, 420, 91, 24))
        self.lineEdit_pressure.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pressure.setObjectName("lineEdit_pressure")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(340, 370, 111, 41))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_temperature = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_temperature.setGeometry(QtCore.QRect(350, 420, 91, 24))
        self.lineEdit_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_temperature.setObjectName("lineEdit_temperature")
        self.lineEdit_humidity = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_humidity.setGeometry(QtCore.QRect(490, 420, 91, 24))
        self.lineEdit_humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_humidity.setObjectName("lineEdit_humidity")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(480, 370, 111, 41))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.frame_altitude = QtWidgets.QFrame(self.groupBox_2)
        self.frame_altitude.setGeometry(QtCore.QRect(20, 30, 131, 341))
        self.frame_altitude.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_altitude.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_altitude.setObjectName("frame_altitude")
        self.frame_pressure = QtWidgets.QFrame(self.groupBox_2)
        self.frame_pressure.setGeometry(QtCore.QRect(160, 30, 161, 341))
        self.frame_pressure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pressure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pressure.setObjectName("frame_pressure")
        self.frame_temperature = QtWidgets.QFrame(self.groupBox_2)
        self.frame_temperature.setGeometry(QtCore.QRect(330, 30, 131, 341))
        self.frame_temperature.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_temperature.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_temperature.setObjectName("frame_temperature")
        self.frame_humidity = QtWidgets.QFrame(self.groupBox_2)
        self.frame_humidity.setGeometry(QtCore.QRect(470, 30, 131, 341))
        self.frame_humidity.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_humidity.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_humidity.setObjectName("frame_humidity")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 250, 321, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_accel_X = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_accel_X.setGeometry(QtCore.QRect(120, 40, 181, 24))
        self.lineEdit_accel_X.setObjectName("lineEdit_accel_X")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 101, 24))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_accel_Y = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_accel_Y.setGeometry(QtCore.QRect(120, 70, 181, 24))
        self.lineEdit_accel_Y.setObjectName("lineEdit_accel_Y")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 101, 24))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 101, 24))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.lineEdit_accel_Z = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_accel_Z.setGeometry(QtCore.QRect(120, 100, 181, 24))
        self.lineEdit_accel_Z.setObjectName("lineEdit_accel_Z")
        self.lineEdit_roll = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_roll.setGeometry(QtCore.QRect(120, 180, 111, 24))
        self.lineEdit_roll.setObjectName("lineEdit_roll")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 150, 101, 24))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_pitch.setGeometry(QtCore.QRect(120, 150, 111, 24))
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 180, 101, 24))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(710, 850, 111, 24))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.label_Status = QtWidgets.QLabel(self.centralwidget)
        self.label_Status.setGeometry(QtCore.QRect(10, 850, 681, 30))
        self.label_Status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Status.setObjectName("label_Status")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 480, 651, 351))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_motor_1 = QtWidgets.QLabel(self.groupBox_4)
        self.label_motor_1.setGeometry(QtCore.QRect(150, 40, 120, 120))
        self.label_motor_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_motor_1.setText("")
        self.label_motor_1.setScaledContents(True)
        self.label_motor_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_motor_1.setObjectName("label_motor_1")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(50, 40, 41, 24))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 130, 81, 24))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.lineEdit_motor_speed_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_speed_1.setGeometry(QtCore.QRect(100, 130, 41, 24))
        self.lineEdit_motor_speed_1.setText("")
        self.lineEdit_motor_speed_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_speed_1.setObjectName("lineEdit_motor_speed_1")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 81, 24))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.lineEdit_motor_gpio_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_gpio_1.setGeometry(QtCore.QRect(100, 70, 41, 24))
        self.lineEdit_motor_gpio_1.setText("")
        self.lineEdit_motor_gpio_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_gpio_1.setObjectName("lineEdit_motor_gpio_1")
        self.lineEdit_motor_id_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_id_1.setGeometry(QtCore.QRect(100, 40, 41, 24))
        self.lineEdit_motor_id_1.setText("")
        self.lineEdit_motor_id_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_id_1.setObjectName("lineEdit_motor_id_1")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(10, 100, 81, 24))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.label_motor_active_1 = QtWidgets.QLabel(self.groupBox_4)
        self.label_motor_active_1.setGeometry(QtCore.QRect(100, 100, 51, 24))
        self.label_motor_active_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_motor_active_1.setObjectName("label_motor_active_1")
        self.label_motor_active_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_motor_active_2.setGeometry(QtCore.QRect(460, 100, 51, 24))
        self.label_motor_active_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_motor_active_2.setObjectName("label_motor_active_2")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(370, 100, 81, 24))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(370, 130, 81, 24))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.lineEdit_motor_speed_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_speed_2.setGeometry(QtCore.QRect(460, 130, 41, 24))
        self.lineEdit_motor_speed_2.setText("")
        self.lineEdit_motor_speed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_speed_2.setObjectName("lineEdit_motor_speed_2")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(370, 70, 81, 24))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.lineEdit_motor_id_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_id_2.setGeometry(QtCore.QRect(460, 40, 41, 24))
        self.lineEdit_motor_id_2.setText("")
        self.lineEdit_motor_id_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_id_2.setObjectName("lineEdit_motor_id_2")
        self.lineEdit_motor_gpio_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_gpio_2.setGeometry(QtCore.QRect(460, 70, 41, 24))
        self.lineEdit_motor_gpio_2.setText("")
        self.lineEdit_motor_gpio_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_gpio_2.setObjectName("lineEdit_motor_gpio_2")
        self.label_motor_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_motor_2.setGeometry(QtCore.QRect(510, 40, 120, 120))
        self.label_motor_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_motor_2.setText("")
        self.label_motor_2.setScaledContents(True)
        self.label_motor_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_motor_2.setObjectName("label_motor_2")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(410, 40, 41, 24))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_motor_active_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_motor_active_3.setGeometry(QtCore.QRect(100, 270, 51, 24))
        self.label_motor_active_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_motor_active_3.setObjectName("label_motor_active_3")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(50, 210, 41, 24))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(10, 240, 81, 24))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.lineEdit_motor_speed_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_speed_3.setGeometry(QtCore.QRect(100, 300, 41, 24))
        self.lineEdit_motor_speed_3.setText("")
        self.lineEdit_motor_speed_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_speed_3.setObjectName("lineEdit_motor_speed_3")
        self.label_motor_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_motor_3.setGeometry(QtCore.QRect(150, 210, 120, 120))
        self.label_motor_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_motor_3.setText("")
        self.label_motor_3.setScaledContents(True)
        self.label_motor_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_motor_3.setObjectName("label_motor_3")
        self.lineEdit_motor_id_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_id_3.setGeometry(QtCore.QRect(100, 210, 41, 24))
        self.lineEdit_motor_id_3.setText("")
        self.lineEdit_motor_id_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_id_3.setObjectName("lineEdit_motor_id_3")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 300, 81, 24))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(10, 270, 81, 24))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.lineEdit_motor_gpio_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_gpio_3.setGeometry(QtCore.QRect(100, 240, 41, 24))
        self.lineEdit_motor_gpio_3.setText("")
        self.lineEdit_motor_gpio_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_gpio_3.setObjectName("lineEdit_motor_gpio_3")
        self.lineEdit_motor_gpio_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_gpio_4.setGeometry(QtCore.QRect(460, 240, 41, 24))
        self.lineEdit_motor_gpio_4.setText("")
        self.lineEdit_motor_gpio_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_gpio_4.setObjectName("lineEdit_motor_gpio_4")
        self.lineEdit_motor_speed_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_speed_4.setGeometry(QtCore.QRect(460, 300, 41, 24))
        self.lineEdit_motor_speed_4.setText("")
        self.lineEdit_motor_speed_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_speed_4.setObjectName("lineEdit_motor_speed_4")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(370, 270, 81, 24))
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_motor_active_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_motor_active_4.setGeometry(QtCore.QRect(460, 270, 51, 24))
        self.label_motor_active_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_motor_active_4.setObjectName("label_motor_active_4")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(410, 210, 41, 24))
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(370, 300, 81, 24))
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.lineEdit_motor_id_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_motor_id_4.setGeometry(QtCore.QRect(460, 210, 41, 24))
        self.lineEdit_motor_id_4.setText("")
        self.lineEdit_motor_id_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_motor_id_4.setObjectName("lineEdit_motor_id_4")
        self.label_motor_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_motor_4.setGeometry(QtCore.QRect(510, 210, 120, 120))
        self.label_motor_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_motor_4.setText("")
        self.label_motor_4.setScaledContents(True)
        self.label_motor_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_motor_4.setObjectName("label_motor_4")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(370, 240, 81, 24))
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MAD-C2 (M1ch3al Autonomous Drone - Command & Control)"))
        self.groupBox.setTitle(_translate("MainWindow", "Navigation"))
        self.label.setText(_translate("MainWindow", "Latitude :"))
        self.label_2.setText(_translate("MainWindow", "Longitude :"))
        self.label_3.setText(_translate("MainWindow", "Speed :"))
        self.label_5.setText(_translate("MainWindow", "GPS mode :"))
        self.label_4.setText(_translate("MainWindow", "GPS status :"))
        self.label_6.setText(_translate("MainWindow", "GPS Time :"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit Application"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Environment data"))
        self.label_7.setText(_translate("MainWindow", "Vehicle\n"
"Altitude (m)"))
        self.label_8.setText(_translate("MainWindow", "Atmospheric\n"
"Pressure (hPa)"))
        self.label_9.setText(_translate("MainWindow", "Environment\n"
"Temperature (°C)"))
        self.label_10.setText(_translate("MainWindow", "Environment\n"
"Humidity (%)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Vehicle stabilization - Accelerometer data"))
        self.label_11.setText(_translate("MainWindow", "Acceleration X :"))
        self.label_12.setText(_translate("MainWindow", "Acceleration Y :"))
        self.label_13.setText(_translate("MainWindow", "Acceleration Z :"))
        self.label_14.setText(_translate("MainWindow", "Pitch :"))
        self.label_15.setText(_translate("MainWindow", "Roll :"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.label_Status.setText(_translate("MainWindow", "Status :"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Motor(s)"))
        self.label_16.setText(_translate("MainWindow", "ID : "))
        self.label_17.setText(_translate("MainWindow", "Speed (%) :"))
        self.label_18.setText(_translate("MainWindow", "GPIO Num :"))
        self.label_19.setText(_translate("MainWindow", "Active :"))
        self.label_motor_active_1.setText(_translate("MainWindow", "False"))
        self.label_motor_active_2.setText(_translate("MainWindow", "False"))
        self.label_20.setText(_translate("MainWindow", "Active :"))
        self.label_22.setText(_translate("MainWindow", "Speed (%) :"))
        self.label_21.setText(_translate("MainWindow", "GPIO Num :"))
        self.label_23.setText(_translate("MainWindow", "ID : "))
        self.label_motor_active_3.setText(_translate("MainWindow", "False"))
        self.label_27.setText(_translate("MainWindow", "ID : "))
        self.label_25.setText(_translate("MainWindow", "GPIO Num :"))
        self.label_26.setText(_translate("MainWindow", "Speed (%) :"))
        self.label_24.setText(_translate("MainWindow", "Active :"))
        self.label_31.setText(_translate("MainWindow", "Active :"))
        self.label_motor_active_4.setText(_translate("MainWindow", "False"))
        self.label_28.setText(_translate("MainWindow", "ID : "))
        self.label_30.setText(_translate("MainWindow", "Speed (%) :"))
        self.label_29.setText(_translate("MainWindow", "GPIO Num :"))

